import {
  bigint,
  boolean,
  doublePrecision,
  integer,
  jsonb,
  numeric,
  pgTable,
  primaryKey,
  text,
  timestamp,
} from "drizzle-orm/pg-core";

const utcTimestamp = (name: string) => timestamp(name, {
  withTimezone: true,
  mode: "string",
});

export const users = pgTable("users", {
  id: text("id").primaryKey(),
  username: text("username").notNull(),
  displayName: text("display_name").notNull(),
  passwordHash: text("password_hash").notNull(),
  isActive: boolean("is_active").notNull().default(true),
  isSuperAdmin: boolean("is_super_admin").notNull().default(false),
  lastLoginAt: utcTimestamp("last_login_at"),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by"),
});

export const labs = pgTable("labs", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").notNull(),
  status: text("status").notNull().default("active"),
  settings: jsonb("settings").$type<Record<string, unknown>>().notNull().default({}),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by"),
});

export const labMemberships = pgTable("lab_memberships", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  userId: text("user_id").notNull(),
  role: text("role").notNull(),
  status: text("status").notNull().default("active"),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by"),
});

export const sessions = pgTable("sessions", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  sessionTokenHash: text("session_token_hash").notNull(),
  expiresAt: utcTimestamp("expires_at").notNull(),
  createdAt: utcTimestamp("created_at").notNull(),
  lastSeenAt: utcTimestamp("last_seen_at"),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  revokedAt: utcTimestamp("revoked_at"),
});

export const projects = pgTable("projects", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  status: text("status").notNull().default("active"),
  metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by"),
});

export const experimentIdentities = pgTable("experiment_identities", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  canonicalLabel: text("canonical_label").notNull(),
  normalizedLabel: text("normalized_label").notNull(),
  aliases: jsonb("aliases").$type<string[]>().notNull().default([]),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by"),
});

export const dataPlans = pgTable("data_plans", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.dataPlan.v2"),
  status: text("status").notNull().default("accepted"),
  task: text("task").notNull().default("experiment_browser_publish"),
  outputShape: text("output_shape").notNull().default("experiment_records"),
  plan: jsonb("plan").$type<Record<string, unknown>>().notNull().default({}),
  sourceEvidence: jsonb("source_evidence").$type<unknown[]>().notNull().default([]),
  operations: jsonb("operations").$type<unknown[]>().notNull().default([]),
  identityBindings: jsonb("identity_bindings").$type<unknown[]>().notNull().default([]),
  dependencyHash: text("dependency_hash").notNull(),
  validation: jsonb("validation").$type<Record<string, unknown>>().notNull().default({}),
  warnings: jsonb("warnings").$type<unknown[]>().notNull().default([]),
  acceptedAt: utcTimestamp("accepted_at"),
  acceptedBy: text("accepted_by"),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by"),
});

export const dataSnapshots = pgTable("data_snapshots", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  dataPlanId: text("data_plan_id"),
  analysisPlanRevisionId: text("analysis_plan_revision_id"),
  analysisRunId: text("analysis_run_id"),
  analysisResultId: text("analysis_result_id"),
  schemaVersion: text("schema_version").notNull().default("labrat.dataSnapshot.v2"),
  status: text("status").notNull().default("accepted"),
  outputShape: text("output_shape").notNull().default("experiment_records"),
  contentHash: text("content_hash").notNull(),
  dependencyHash: text("dependency_hash").notNull(),
  snapshot: jsonb("snapshot").$type<Record<string, unknown>>().notNull().default({}),
  experimentRecords: jsonb("experiment_records").$type<Array<Record<string, unknown>>>().notNull().default([]),
  sourceRefs: jsonb("source_refs").$type<unknown[]>().notNull().default([]),
  summary: jsonb("summary").$type<Record<string, unknown>>().notNull().default({}),
  warnings: jsonb("warnings").$type<unknown[]>().notNull().default([]),
  acceptedAt: utcTimestamp("accepted_at").notNull(),
  acceptedBy: text("accepted_by").notNull(),
  createdAt: utcTimestamp("created_at").notNull(),
  createdBy: text("created_by").notNull(),
});

export const experimentSnapshotHeads = pgTable("experiment_snapshot_heads", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  experimentId: text("experiment_id").notNull(),
  dataSnapshotId: text("data_snapshot_id").notNull(),
  recordIndex: integer("record_index").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  updatedBy: text("updated_by").notNull(),
});

export const browserViews = pgTable("browser_views", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  ownerUserId: text("owner_user_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.browserView.v1"),
  name: text("name").notNull(),
  payload: jsonb("payload").$type<Record<string, unknown>>().notNull().default({}),
  isDefault: boolean("is_default").notNull().default(false),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
});

export const projectBrowserConfigs = pgTable("project_browser_configs", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.projectBrowserConfig.v1"),
  payload: jsonb("payload").$type<Record<string, unknown>>().notNull().default({}),
  version: integer("version").notNull().default(1),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  updatedBy: text("updated_by"),
});

export const experimentAnnotations = pgTable("experiment_annotations", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  userId: text("user_id").notNull(),
  experimentId: text("experiment_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.experimentAnnotation.v1"),
  note: text("note").notNull().default(""),
  color: text("color").notNull().default("amber"),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
});

export const experimentCustomColumns = pgTable("experiment_custom_columns", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.experimentCustomColumn.v1"),
  label: text("label").notNull(),
  version: integer("version").notNull().default(1),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by"),
  updatedBy: text("updated_by"),
});

export const experimentCustomValues = pgTable("experiment_custom_values", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  customColumnId: text("custom_column_id").notNull(),
  experimentId: text("experiment_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.experimentCustomValue.v1"),
  value: text("value").notNull().default(""),
  version: integer("version").notNull().default(1),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by"),
  updatedBy: text("updated_by"),
});

export const fileObjects = pgTable("file_objects", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  originalName: text("original_name").notNull(),
  mimeType: text("mime_type"),
  extension: text("extension"),
  sizeBytes: bigint("size_bytes", { mode: "number" }).notNull(),
  checksumSha256: text("checksum_sha256").notNull(),
  storageProvider: text("storage_provider").notNull().default("local"),
  storageKey: text("storage_key").notNull(),
  metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
  createdAt: utcTimestamp("created_at").notNull(),
  createdBy: text("created_by").notNull(),
});

export const importRuns = pgTable("import_runs", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  fileObjectId: text("file_object_id"),
  status: text("status").notNull(),
  scanResult: jsonb("scan_result").$type<Record<string, unknown>>(),
  normalizePreview: jsonb("normalize_preview").$type<Record<string, unknown>>(),
  reviewDecisions: jsonb("review_decisions").$type<Record<string, unknown>>().notNull().default({}),
  warnings: jsonb("warnings").$type<unknown[]>().notNull().default([]),
  error: jsonb("error").$type<Record<string, unknown>>(),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by"),
});

export const chartSpecs = pgTable("chart_specs", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  title: text("title"),
  chartType: text("chart_type").notNull(),
  spec: jsonb("spec").$type<Record<string, unknown>>().notNull(),
  layout: jsonb("layout").$type<Record<string, unknown>>().notNull().default({}),
  warnings: jsonb("warnings").$type<unknown[]>().notNull().default([]),
  analysisResultId: text("analysis_result_id"),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by"),
});

export const chartStyleProfiles = pgTable("chart_style_profiles", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.chartStyleProfile.v1"),
  name: text("name").notNull(),
  description: text("description").notNull().default(""),
  status: text("status").notNull().default("active"),
  currentVersionId: text("current_version_id"),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by"),
  updatedBy: text("updated_by"),
});

export const chartStyleProfileVersions = pgTable("chart_style_profile_versions", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  chartStyleProfileId: text("chart_style_profile_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.chartStyleProfileVersion.v1"),
  version: integer("version").notNull(),
  status: text("status").notNull().default("accepted"),
  payload: jsonb("payload").$type<Record<string, unknown>>().notNull().default({}),
  contentHash: text("content_hash").notNull(),
  createdAt: utcTimestamp("created_at").notNull(),
  createdBy: text("created_by"),
  acceptedAt: utcTimestamp("accepted_at"),
  acceptedBy: text("accepted_by"),
});

export const reusableChartTemplates = pgTable("reusable_chart_templates", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.reusableChartTemplate.v1"),
  name: text("name").notNull(),
  description: text("description").notNull().default(""),
  status: text("status").notNull().default("active"),
  currentVersionId: text("current_version_id"),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by"),
  updatedBy: text("updated_by"),
});

export const reusableChartTemplateVersions = pgTable("reusable_chart_template_versions", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  reusableChartTemplateId: text("reusable_chart_template_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.reusableChartTemplateVersion.v1"),
  version: integer("version").notNull(),
  status: text("status").notNull().default("accepted"),
  sourceChartSpecId: text("source_chart_spec_id").notNull(),
  chartStyleProfileVersionId: text("chart_style_profile_version_id"),
  payload: jsonb("payload").$type<Record<string, unknown>>().notNull().default({}),
  contentHash: text("content_hash").notNull(),
  createdAt: utcTimestamp("created_at").notNull(),
  createdBy: text("created_by"),
  acceptedAt: utcTimestamp("accepted_at").notNull(),
  acceptedBy: text("accepted_by"),
});

export const reusableChartTemplateSlotBindings = pgTable("reusable_chart_template_slot_bindings", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  reusableChartTemplateVersionId: text("reusable_chart_template_version_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.reusableChartTemplateSlotBinding.v1"),
  slotId: text("slot_id").notNull(),
  columnId: text("column_id").notNull(),
  valueType: text("value_type").notNull(),
  unit: text("unit"),
  sourceSignature: text("source_signature").notNull(),
  status: text("status").notNull().default("active"),
  createdAt: utcTimestamp("created_at").notNull(),
  createdBy: text("created_by"),
});

export const reusableChartTemplateApplications = pgTable("reusable_chart_template_applications", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  reusableChartTemplateVersionId: text("reusable_chart_template_version_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.reusableChartTemplateApplication.v1"),
  status: text("status").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  requestHash: text("request_hash").notNull(),
  experimentIds: jsonb("experiment_ids").$type<string[]>().notNull().default([]),
  frozenHeadRefs: jsonb("frozen_head_refs").$type<unknown[]>().notNull().default([]),
  bindings: jsonb("bindings").$type<unknown[]>().notNull().default([]),
  compatibility: jsonb("compatibility").$type<Record<string, unknown>>().notNull().default({}),
  analysisThreadId: text("analysis_thread_id"),
  analysisPlanRevisionId: text("analysis_plan_revision_id"),
  analysisRunId: text("analysis_run_id"),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by"),
  updatedBy: text("updated_by"),
});

export const manuscripts = pgTable("manuscripts", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  title: text("title").notNull(),
  status: text("status").notNull().default("draft"),
  blocks: jsonb("blocks").$type<unknown[]>().notNull().default([]),
  pages: jsonb("pages").$type<unknown[]>().notNull().default([]),
  canvasState: jsonb("canvas_state").$type<Record<string, unknown>>().notNull().default({}),
  referencesPayload: jsonb("references_payload").$type<unknown[]>().notNull().default([]),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by"),
});

export const sourceDocuments = pgTable("source_documents", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  fileObjectId: text("file_object_id"),
  importRunId: text("import_run_id"),
  documentType: text("document_type").notNull().default("excel_workbook"),
  indexVersion: text("index_version").notNull().default("labrat.sourceIndex.v1"),
  status: text("status").notNull().default("indexed"),
  metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
  summary: jsonb("summary").$type<Record<string, unknown>>().notNull().default({}),
  warnings: jsonb("warnings").$type<unknown[]>().notNull().default([]),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by"),
  updatedBy: text("updated_by"),
});

export const sourceRegions = pgTable("source_regions", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  sourceDocumentId: text("source_document_id").notNull(),
  importRunId: text("import_run_id"),
  regionKey: text("region_key"),
  kind: text("kind").notNull().default("unknown_region"),
  label: text("label"),
  sheetName: text("sheet_name"),
  rangeRef: text("range_ref"),
  startRow: integer("start_row"),
  endRow: integer("end_row"),
  startCol: integer("start_col"),
  endCol: integer("end_col"),
  confidence: numeric("confidence"),
  signals: jsonb("signals").$type<Record<string, unknown>>().notNull().default({}),
  candidateFields: jsonb("candidate_fields").$type<unknown[]>().notNull().default([]),
  sourceRefs: jsonb("source_refs").$type<unknown[]>().notNull().default([]),
  warnings: jsonb("warnings").$type<unknown[]>().notNull().default([]),
  status: text("status").notNull().default("active"),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by"),
  updatedBy: text("updated_by"),
});

export const sourceIndexBlobs = pgTable("source_index_blobs", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  sourceDocumentId: text("source_document_id").notNull(),
  blobKind: text("blob_kind").notNull(),
  storageProvider: text("storage_provider").notNull().default("database"),
  storageKey: text("storage_key"),
  payload: jsonb("payload").$type<Record<string, unknown>>(),
  checksumSha256: text("checksum_sha256"),
  createdAt: utcTimestamp("created_at").notNull(),
  createdBy: text("created_by"),
});

export const agentRuns = pgTable("agent_runs", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.agentRun.v1"),
  status: text("status").notNull().default("waiting_for_user"),
  mode: text("mode"),
  userMessage: text("user_message").notNull().default(""),
  selectedContext: jsonb("selected_context").$type<Record<string, unknown>>().notNull().default({}),
  visibleSteps: jsonb("visible_steps").$type<unknown[]>().notNull().default([]),
  toolTrace: jsonb("tool_trace").$type<unknown[]>().notNull().default([]),
  proposalRefs: jsonb("proposal_refs").$type<unknown[]>().notNull().default([]),
  actions: jsonb("actions").$type<unknown[]>().notNull().default([]),
  usage: jsonb("usage").$type<Record<string, unknown>>().notNull().default({}),
  warnings: jsonb("warnings").$type<unknown[]>().notNull().default([]),
  error: jsonb("error").$type<Record<string, unknown>>(),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by"),
  updatedBy: text("updated_by"),
});

export const workbookReviewSessions = pgTable("workbook_review_sessions", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  sourceDocumentId: text("source_document_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.workbookReviewSession.v1"),
  status: text("status").notNull().default("needs_user_review"),
  version: integer("version").notNull().default(1),
  workbookSummary: jsonb("workbook_summary").$type<Record<string, unknown>>().notNull().default({}),
  messages: jsonb("messages").$type<unknown[]>().notNull().default([]),
  warnings: jsonb("warnings").$type<unknown[]>().notNull().default([]),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by"),
  updatedBy: text("updated_by"),
});

export const workbookReviewRegions = pgTable("workbook_review_regions", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  workbookReviewSessionId: text("workbook_review_session_id").notNull(),
  sourceDocumentId: text("source_document_id").notNull(),
  sourceRegionId: text("source_region_id"),
  sheetName: text("sheet_name").notNull(),
  rangeRef: text("range_ref").notNull(),
  selectionMethod: text("selection_method").notNull().default("manual"),
  disposition: text("disposition").notNull().default("active"),
  reviewStatus: text("review_status").notNull().default("interpreting"),
  currentRevisionId: text("current_revision_id"),
  acceptedRevisionId: text("accepted_revision_id"),
  version: integer("version").notNull().default(1),
  warnings: jsonb("warnings").$type<unknown[]>().notNull().default([]),
  interpretationHint: jsonb("interpretation_hint").$type<Record<string, unknown>>().notNull().default({}),
  acceptedAt: utcTimestamp("accepted_at"),
  acceptedBy: text("accepted_by"),
  ignoredAt: utcTimestamp("ignored_at"),
  ignoredBy: text("ignored_by"),
  ignoredReason: text("ignored_reason"),
  deletedAt: utcTimestamp("deleted_at"),
  deletedBy: text("deleted_by"),
  deletedReason: text("deleted_reason"),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by"),
  updatedBy: text("updated_by"),
});

export const regionUnderstandingRevisions = pgTable("region_understanding_revisions", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  workbookReviewSessionId: text("workbook_review_session_id").notNull(),
  sourceDocumentId: text("source_document_id").notNull(),
  regionId: text("region_id").notNull(),
  revisionNumber: integer("revision_number").notNull(),
  trigger: text("trigger").notNull().default("initial"),
  userFeedback: text("user_feedback").notNull().default(""),
  summary: jsonb("summary").$type<unknown[]>().notNull().default([]),
  interpretation: jsonb("interpretation").$type<Record<string, unknown>>().notNull().default({}),
  sourceRefs: jsonb("source_refs").$type<unknown[]>().notNull().default([]),
  sourceContentHash: text("source_content_hash").notNull(),
  dependencyHash: text("dependency_hash").notNull(),
  validation: jsonb("validation").$type<Record<string, unknown>>().notNull().default({}),
  provider: jsonb("provider").$type<Record<string, unknown>>().notNull().default({}),
  warnings: jsonb("warnings").$type<unknown[]>().notNull().default([]),
  confidence: doublePrecision("confidence"),
  createdAt: utcTimestamp("created_at").notNull(),
  createdBy: text("created_by"),
});

export const analysisThreads = pgTable("analysis_threads", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.analysisThread.v1"),
  status: text("status").notNull().default("planning"),
  originalRequest: text("original_request").notNull(),
  messages: jsonb("messages").$type<unknown[]>().notNull().default([]),
  planRevisionIds: jsonb("plan_revision_ids").$type<string[]>().notNull().default([]),
  analysisRunIds: jsonb("analysis_run_ids").$type<string[]>().notNull().default([]),
  acceptedAnalysisResultIds: jsonb("accepted_analysis_result_ids").$type<string[]>().notNull().default([]),
  chartSpecIds: jsonb("chart_spec_ids").$type<string[]>().notNull().default([]),
  outputTarget: text("output_target").notNull().default("chart"),
  inputMode: text("input_mode"),
  dataSnapshotIds: jsonb("data_snapshot_ids").$type<string[]>().notNull().default([]),
  browserViewIds: jsonb("browser_view_ids").$type<string[]>().notNull().default([]),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by"),
});

export const analysisPlanRevisions = pgTable("analysis_plan_revisions", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  analysisThreadId: text("analysis_thread_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.analysisPlanRevision.v1"),
  revision: integer("revision").notNull(),
  status: text("status").notNull().default("awaiting_review"),
  requestSummary: text("request_summary").notNull(),
  plan: jsonb("plan").$type<Record<string, unknown>>().notNull(),
  sourceRectangles: jsonb("source_rectangles").$type<unknown[]>().notNull().default([]),
  feedback: text("feedback"),
  warnings: jsonb("warnings").$type<unknown[]>().notNull().default([]),
  validation: jsonb("validation").$type<Record<string, unknown>>().notNull().default({}),
  outputTarget: text("output_target").notNull().default("chart"),
  acceptedAt: utcTimestamp("accepted_at"),
  acceptedBy: text("accepted_by"),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by"),
});

export const analysisRuns = pgTable("analysis_runs", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  analysisThreadId: text("analysis_thread_id").notNull(),
  acceptedPlanRevisionId: text("accepted_plan_revision_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.analysisRun.v1"),
  status: text("status").notNull().default("queued"),
  idempotencyKey: text("idempotency_key").notNull(),
  requestHash: text("request_hash").notNull(),
  inputHash: text("input_hash").notNull(),
  programHash: text("program_hash").notNull(),
  runtimeVersion: text("runtime_version").notNull(),
  resultPreviewHash: text("result_preview_hash"),
  payload: jsonb("payload").$type<Record<string, unknown>>().notNull().default({}),
  warnings: jsonb("warnings").$type<unknown[]>().notNull().default([]),
  validation: jsonb("validation").$type<Record<string, unknown>>().notNull().default({}),
  outputTarget: text("output_target").notNull().default("chart"),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by"),
});

export const analysisResults = pgTable("analysis_results", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  analysisThreadId: text("analysis_thread_id").notNull(),
  analysisRunId: text("analysis_run_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.analysisResult.v1"),
  status: text("status").notNull().default("awaiting_review"),
  contentHash: text("content_hash").notNull(),
  resultPreviewHash: text("result_preview_hash"),
  result: jsonb("result").$type<Record<string, unknown>>().notNull(),
  sourceRefs: jsonb("source_refs").$type<unknown[]>().notNull().default([]),
  warnings: jsonb("warnings").$type<unknown[]>().notNull().default([]),
  validation: jsonb("validation").$type<Record<string, unknown>>().notNull().default({}),
  outputTarget: text("output_target").notNull().default("chart"),
  acceptedAt: utcTimestamp("accepted_at"),
  acceptedBy: text("accepted_by"),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by"),
});

export const analysisPublications = pgTable("analysis_publications", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  analysisThreadId: text("analysis_thread_id").notNull(),
  analysisResultId: text("analysis_result_id").notNull(),
  chartSpecId: text("chart_spec_id").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  requestHash: text("request_hash").notNull(),
  response: jsonb("response").$type<Record<string, unknown>>().notNull().default({}),
  createdAt: utcTimestamp("created_at").notNull(),
  createdBy: text("created_by").notNull(),
});

export const analysisThreadRetryReceipts = pgTable("analysis_thread_retry_receipts", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  analysisThreadId: text("analysis_thread_id").notNull(),
  actorUserId: text("actor_user_id").notNull(),
  schemaVersion: text("schema_version").notNull().default("labrat.analysisThreadRetryReceipt.v1"),
  idempotencyKey: text("idempotency_key").notNull(),
  requestHash: text("request_hash").notNull(),
  status: text("status").notNull(),
  leaseExpiresAt: utcTimestamp("lease_expires_at"),
  attemptCount: integer("attempt_count").notNull().default(1),
  analysisPlanRevisionId: text("analysis_plan_revision_id"),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
});

export const analysisExperimentPublications = pgTable("analysis_experiment_publications", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  analysisThreadId: text("analysis_thread_id").notNull(),
  analysisResultId: text("analysis_result_id").notNull(),
  dataSnapshotId: text("data_snapshot_id").notNull(),
  browserViewId: text("browser_view_id").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  requestHash: text("request_hash").notNull(),
  response: jsonb("response").$type<Record<string, unknown>>().notNull().default({}),
  createdAt: utcTimestamp("created_at").notNull(),
  createdBy: text("created_by").notNull(),
});

export const experimentSnapshotPublishes = pgTable("experiment_snapshot_publishes", {
  projectId: text("project_id").notNull(),
  labId: text("lab_id").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  requestHash: text("request_hash").notNull(),
  dataPlanId: text("data_plan_id").notNull(),
  dataSnapshotId: text("data_snapshot_id").notNull(),
  response: jsonb("response").$type<Record<string, unknown>>().notNull().default({}),
  createdAt: utcTimestamp("created_at").notNull(),
}, (table) => [primaryKey({ columns: [table.projectId, table.idempotencyKey] })]);

export const schemaMigrations = pgTable("labrat_schema_migrations", {
  filename: text("filename").primaryKey(),
  checksum: text("checksum").notNull(),
  appliedAt: utcTimestamp("applied_at").notNull(),
});

export const auditEvents = pgTable("audit_events", {
  id: text("id").primaryKey(),
  labId: text("lab_id"),
  projectId: text("project_id"),
  actorUserId: text("actor_user_id"),
  action: text("action").notNull(),
  targetType: text("target_type"),
  targetId: text("target_id"),
  summary: text("summary"),
  metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
  createdAt: utcTimestamp("created_at").notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
});

export const labGroups = pgTable("lab_groups", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  name: text("name").notNull(),
  description: text("description").notNull().default(""),
  status: text("status").notNull().default("active"),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by"),
  updatedBy: text("updated_by"),
});

export const labGroupMembers = pgTable("lab_group_members", {
  groupId: text("group_id").notNull(),
  labId: text("lab_id").notNull(),
  userId: text("user_id").notNull(),
  status: text("status").notNull().default("active"),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by"),
  updatedBy: text("updated_by"),
}, (table) => [primaryKey({ columns: [table.groupId, table.userId] })]);

export const projectAccessGrants = pgTable("project_access_grants", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  userId: text("user_id"),
  groupId: text("group_id"),
  scope: text("scope").notNull(),
  capabilities: jsonb("capabilities").$type<string[]>().notNull().default([]),
  status: text("status").notNull().default("active"),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by"),
  updatedBy: text("updated_by"),
});

export const experimentAccessGrants = pgTable("experiment_access_grants", {
  id: text("id").primaryKey(),
  labId: text("lab_id").notNull(),
  projectId: text("project_id").notNull(),
  experimentId: text("experiment_id").notNull(),
  userId: text("user_id"),
  groupId: text("group_id"),
  capabilities: jsonb("capabilities").$type<string[]>().notNull().default([]),
  status: text("status").notNull().default("active"),
  createdAt: utcTimestamp("created_at").notNull(),
  updatedAt: utcTimestamp("updated_at").notNull(),
  createdBy: text("created_by"),
  updatedBy: text("updated_by"),
});

export const invitations = pgTable("invitations", {
  id: text("id").primaryKey(),
  codeHash: text("code_hash").notNull(),
  kind: text("kind").notNull(),
  labId: text("lab_id"),
  createdBy: text("created_by").notNull(),
  createdAt: utcTimestamp("created_at").notNull(),
  expiresAt: utcTimestamp("expires_at").notNull(),
  revokedAt: utcTimestamp("revoked_at"),
  revokedBy: text("revoked_by"),
  redeemedAt: utcTimestamp("redeemed_at"),
  redeemedBy: text("redeemed_by"),
  redeemedLabId: text("redeemed_lab_id"),
});

export const v1Schema = {
  invitations,
  users,
  labs,
  labMemberships,
  sessions,
  projects,
  fileObjects,
  importRuns,
  chartSpecs,
  chartStyleProfiles,
  chartStyleProfileVersions,
  reusableChartTemplates,
  reusableChartTemplateVersions,
  reusableChartTemplateSlotBindings,
  reusableChartTemplateApplications,
  manuscripts,
  sourceDocuments,
  sourceRegions,
  sourceIndexBlobs,
  agentRuns,
  workbookReviewSessions,
  workbookReviewRegions,
  regionUnderstandingRevisions,
  dataPlans,
  dataSnapshots,
  experimentIdentities,
  experimentSnapshotHeads,
  browserViews,
  projectBrowserConfigs,
  experimentAnnotations,
  experimentCustomColumns,
  experimentCustomValues,
  experimentSnapshotPublishes,
  analysisThreads,
  analysisPlanRevisions,
  analysisRuns,
  analysisResults,
  analysisPublications,
  analysisThreadRetryReceipts,
  analysisExperimentPublications,
  auditEvents,
  labGroups,
  labGroupMembers,
  projectAccessGrants,
  experimentAccessGrants,
  schemaMigrations,
};
